### ISSUE TITLE
potentiality for multiple patch windows in same month?

### ISSUE THREAD

**Issue by xandrellas** [puppetlabs/puppetlabs-patching_as_code#17]
Looking at the is_patchday.rb it appears to follow a monthly-based cycle.  Is there a means to shrink or expand that cycle?  Such as - I'd like this particular patch group to be patched twice a month?

**Comment by kreeuwijk** [comment]
That's interesting for sure. Can you detail what that would look like in your view?
So what you'd like to be able to control, how it should behave and how you'd write it in Hiera.

For example, to (theoretically) patch every 2nd and 4th Thursday of the month:
```
patching_as_code::patch_schedule:
  twice_a_month:
    day_of_week: Thursday
    count_of_week:
        - 2
        - 4
    hours: 10:00 - 11:00
    max_runs: 1
    reboot: ifneeded
```
